name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: '0.2.6-rc.1' # optional
          docker_compose: 'docker-compose.yml' # required
          repo_token: "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"
